<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #ddd; padding-bottom: 20px; }
        .metrics { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }
        .metric { background: #f8f9fa; padding: 15px; border-radius: 8px; text-align: center; }
        .metric-value { font-size: 24px; font-weight: bold; color: #2563eb; }
        .metric-label { font-size: 14px; color: #6b7280; margin-top: 5px; }
        .footer { margin-top: 40px; text-align: center; color: #6b7280; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p><strong>{{ $branch }}</strong></p>
        <p>{{ $period }}</p>
        <p>Generated: {{ $generated_at }}</p>
    </div>

    <div class="metrics">
        <div class="metric">
            <div class="metric-value">{{ number_format($metrics['total_bookings']) }}</div>
            <div class="metric-label">Total Bookings</div>
        </div>
        
        <div class="metric">
            <div class="metric-value">{{ number_format($metrics['completed_bookings']) }}</div>
            <div class="metric-label">Completed Bookings</div>
        </div>
        
        <div class="metric">
            <div class="metric-value">{{ number_format($metrics['cancelled_bookings']) }}</div>
            <div class="metric-label">Cancelled Bookings</div>
        </div>
        
        <div class="metric">
            <div class="metric-value">{{ number_format($metrics['no_show_bookings']) }}</div>
            <div class="metric-label">No-Show Bookings</div>
        </div>
        
        <div class="metric">
            <div class="metric-value">KES {{ number_format($metrics['total_revenue'], 2) }}</div>
            <div class="metric-label">Total Revenue</div>
        </div>
        
        <div class="metric">
            <div class="metric-value">KES {{ number_format($metrics['average_booking_value'], 2) }}</div>
            <div class="metric-label">Average Booking Value</div>
        </div>
        
        <div class="metric">
            <div class="metric-value">{{ number_format($metrics['unique_clients']) }}</div>
            <div class="metric-label">Unique Clients</div>
        </div>
        
        <div class="metric">
            <div class="metric-value">{{ number_format($metrics['completion_rate'], 1) }}%</div>
            <div class="metric-label">Completion Rate</div>
        </div>
    </div>

    <div class="footer">
        <p>Report generated by Wellness Spa Admin System</p>
    </div>
</body>
</html>